sudo: required
services:
  - docker
  - mysql
dist: xenial

before_install:
  - docker-compose up -d
  - docker exec -it order-service npm run test
  - docker exec -i order-service npm run test:e2e

script:
  echo hi
