sudo: required
services:
  - docker

before_install:
  - docker-compose up -d
  - sudo service mysql start
  - docker exec -i mysql-service mysql -u root -psecretpassword

script:
  - docker exec -it order-service npm run test
