sudo: required
services:
  - docker
  - mysql

before_install:
  - docker-compose up -d
  - docker exec -i mysql-service mysql -u root -psecretpassword

script:
  - docker exec -it order-service npm run test
