sudo: required
services:
  - docker
  - mysql
dist: xenial

before_install:
  - docker-compose up -d
  - service mysql status
  - docker exec -i mysql-service mysql --host 0.0.0.0 -u root -psecretpassword
