branches:
  only:
  - master
sudo: required
services:
  - docker
  - mysql
dist: xenial

before_install:
  - docker-compose up -d

script:
  - docker exec -it order-service npm run test
  - docker exec -i order-service npm run test:e2e

after_success:
   - echo "$DOCKER_HUB_PW" | docker login -u "$DOCKER_HUB_ID" --password-stdin
   - docker images
   - docker push hkityan/order-service

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: order-service
  env: OrderService-env-1
  bucket_name: elasticbeanstalk-ap-south-1-203818373774
  bucket_path: order-service
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

