sudo: required
services:
  - docker

before_install:
  - docker-compose up -d
  - docker ps
  - sleep 1
  - docker exec -i mysql-service mysql -u root -psecretpassword order_delivery < test_data.sql

script:
  - docker exec -it order-service npm run test
