version: "3.1"
services:
  order-service:
    build:
      context: .
    image: hkityan/order-service
    container_name: order-service-dev
    ports:
      - 8080:8080
    command: ["npm", "run", "start:dev"]
    # allow watching local directory for continous update
    volumes:
      - /order-service/node_modules
      - .:/order-service
    depends_on:
      - mysql-service
  mysql-service:
    image: mysql:5.7.30
    restart: always
    container_name: mysql-service-dev
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - orderdb:/var/lib/orderdb
    ports:
      - 3307:3306 # allow db client to connect to mysql
volumes:
  orderdb: