version: "3.1"
services:
  order-service:
    build:
      context: .
    image: hkityan/order-service
    container_name: order-service-dev
    ports:
      - 8080:8080
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./src:/order-service/src
    depends_on:
      - mysql-service
  mysql-service:
    image: mysql:5.7.30
    restart: always
    container_name: mysql-service-dev
    environment: # in production, environment variables will be store in instance
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: order_delivery
    volumes:
      - orderdbdev:/var/lib/mysql
    ports:
      - 3307:3306 # allow db client to connect to mysql
volumes:
  orderdbdev: